Restorant/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Restorant.Application.IServices;
using Restorant.Application.Services;
using Restorant.DTOs.CategoryDtos;
using Restorant.DTOs.MenuItemDtos;

namespace Restorant.Controllers
{
    public class CategoryController : Controller
    {

        private readonly ICategoryService _catService;

        public CategoryController(ICategoryService catService)
        {
            _catService = catService;
        }

        public async Task<IActionResult> GetAllCategories()
        {
            var cat = await _catService.GetAllCategoriesAsync();

            return View(cat);
        }

        public async Task<IActionResult> Create()
        {
            CreateCategoryDto Cat = new CreateCategoryDto();
            return View(Cat);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateCategoryDto cat)
        {
            if (ModelState.IsValid == true)
            {
                await _catService.CreateCategoriesAsync(cat);
                return RedirectToAction("GetAllCategories");

            }
            else
            {
                return View("Create", cat);
            }

        }

        public async Task<IActionResult> Edit(int id)
        {
            var editeingCat = await _catService.GetCategoryById(id);

            return View(editeingCat);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(GetAllCategoriesDto cat)
        {
            await _catService.UpdateCategoriesAsync(cat);
            return RedirectToAction("GetAllCategories");
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _catService.DeleteCategoriesAsync(id);
            return  RedirectToAction("GetAllCategories");
        }

        

    }
}

Restorant/Controllers/MealController.cs
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using Restorant.Application.IServices;
using Restorant.Data;
using Restorant.DTOs.MenuItemDtos;
using Restorant.Models;
using Restorant.ViewModels;
using System.Text;

namespace Restorant.Controllers
{
    public class MealController : Controller
    {
        private readonly IMenuItemService _menuItemService;
        private readonly ICategoryService _catService;

        public MealController(IMenuItemService menuItemService, ICategoryService catService)
        {
            _menuItemService = menuItemService;
            _catService = catService;
        }


        //[Authorize]
        public async Task<IActionResult> GetAllMeals()
        {
            var meals = await _menuItemService.GetAllMenuItemsAsync();


            return View(meals);
        }

        
        public async Task<IActionResult> Create()
        {

            CreateMenuItemDto mealCat = new CreateMenuItemDto();
            var Categories = await _catService.GetAllCategoriesAsync() ;
            mealCat.Categories = Categories.ToList();
            return View(mealCat);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateMenuItemDto menuItem)
        {
            if (ModelState.IsValid == true)
            {
                if (menuItem.CategoryId != 0)
                {
                    await _menuItemService.CreateAsync(menuItem);
                    return RedirectToAction("GetAllMeals");
                }
                else
                {
                    ModelState.AddModelError("CategoryId", "Select Category");
                    var Categories = await _catService.GetAllCategoriesAsync();
                    menuItem.Categories = Categories.ToList();
                    return View("Create", menuItem);
                }
                
            }
            else
            {

                var Categories = await _catService.GetAllCategoriesAsync();
                //menuItem.Categories = Categories.ToList();
                return View("Create", menuItem);
            }
            
        }

        public async Task<IActionResult> MenuItems()
        {
            var meals = await _menuItemService.MenuItemsAsync();

            return View(meals);
        }



        //public IActionResult Details(int id)
        //{
        //    var menuItem = _context.MenuItems.FirstOrDefault(m => m.Id == id);
        //    DetailsMenuItemWithSameItem bmt = new();
        //    bmt.MenuItem.Categories = _context.Categories.ToList();
        //    var category = _context.Categories.FirstOrDefault(c => c.Id == menuItem.CategoryId);
        //    //if(category.Name == "Chicken Burgers" || category.Name == "Beef Burgers")
        //    //{
        //    //    mealCat.Size = menuItem.Size;
        //    //}
        //    bmt.MenuItem.Name = menuItem.Name;
        //    bmt.MenuItem.Price = menuItem.Price;
        //    bmt.MenuItem.Size = menuItem.Size;
        //    bmt.MenuItem.ImageUrl = menuItem.ImageUrl;
        //    bmt.MenuItem.Description = menuItem.Description;
        //    bmt.MenuItem.CategoryId = menuItem.CategoryId;
        //    bmt.SameItems = _context.MenuItems.Where(c => c.Category.Name == category.Name).ToList();
        //    StringBuilder rename = new StringBuilder();
        //    ViewBag.cateName = category.Name;
        //    ViewBag.rename = rename;
        //    return View(bmt);
        //}

        public async Task <IActionResult> Edit(int id)
        {
            var editeingItem = await _menuItemService.GetByIdAsync(id);
            editeingItem.Categories = await _catService.GetAllCategoriesAsync();

            return View(editeingItem);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UpdateMenuItemDto menuItem)
        {
            await _menuItemService.UpdateAsync(menuItem);
            return RedirectToAction("GetAllMeals");
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _menuItemService.DeleteAsync(id);
            return RedirectToAction("GetAllMeals");
        }

        public async Task<IActionResult> CategoryItems(int id)
        {
            var items = (await _menuItemService.MenuItemsAsync()).ToList();
            
             var catItems = items.Where(items => items.CategoryId == id).ToList();
            return View("MenuItems", catItems);
        }
    }
}

Restorant/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Restorant.DTOs.UserDtos;

namespace Restorant.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManger;

        public RoleController(RoleManager<IdentityRole> roleManger)
        {
            this.roleManger = roleManger;
        }
        public IActionResult AddRole()
        {
            return View();
        }

        [HttpPost]
        public async Task <IActionResult> AddRole(Role role)
        {
            if(ModelState.IsValid)
            {
              IdentityResult result = await roleManger.CreateAsync(new IdentityRole(role.RoleName));
                if(result.Succeeded)
                {
                    ViewBag.sucess = true;
                    return RedirectToAction("Index", "Home");
                }
                foreach(var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View("AddRole", role);
        }
        [Authorize(Roles = "Admin")]
        public IActionResult AdminAuton()
        {
            return View();
        }
    }
}

Restorant/Views/Role/AddRole.cshtml
@using Restorant.DTOs.UserDtos
@model Role

<style>
    .form-group
    {
        margin-bottom:20px;
        width: 400px;
        
    }

    .input{
        background-color:wheat
    }
</style>
<section class="" style="margin-top:50px;padding-top:100px;background-color:black">
    
    <form asp-action="AddRole" style="justify-items:center;padding-bottom:50px ;color: #df5f04;">
        <h2>Login</h2>
                <div class="form-group">
                    <label asp-for="RoleName" class="control-label"></label>
                    <input asp-for="RoleName" class="form-control" />
                    <span asp-validation-for="RoleName" class="text-danger"></span>
                </div>

                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <input type="submit" value="AddRole" class="btn " style="background-color: #df5f04; padding:10px" />
                </div>
                <div>
                     <a asp-action="RoleRegister" style="color:  #df5f04">If you have not account click here to SingIn</a>
                </div>

            </form>
       
   
</section>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Restorant/Views/Role/AdminAuton.cshtml
<style>
    .role{
                border: 2px solid orange;
        padding: 20px;
        text-align: center;;
        background-color:black;
        border-radius: 10px;
        box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.1);
        transition: transform 0.2s;
    }
    .a_role{
        text-decoration: none;
        color: white;
    }
</style>


<section style="width:100%; background-color:black; padding:200px">
  <article class="container" style="display:flex; justify-content:space-around">
        <a class="a_role" asp-action="GetAllCategories" asp-controller="Category">
            <div class="role">
                <i class="bi bi-table" style="font-size:50px; color:ghostwhite"></i>
              <h2>Categories</h2>
          </div>
      </a>
        <a class="a_role" asp-action="GetAllMeals" asp-controller="Meal">
            <div class="role">
                <i class="bi bi-fork-knife" style="font-size:50px; color:orange"></i>
                <h2>MenuItems</h2>
            </div>
      </a>
        <a class="a_role" asp-action="" asp-controller="">
            <div class="role">
                <i class="bi bi-bar-chart-line-fill" style="font-size:50px; color:orang"></i>
                <h2>Orders</h2>
            </div>
      </a>

  </article>
</section>