Restorant/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Restorant.Application.IServices;
using Restorant.Application.Services;
using Restorant.DTOs.CategoryDtos;
using Restorant.DTOs.MenuItemDtos;

namespace Restorant.Controllers
{
    public class CategoryController : Controller
    {

        private readonly ICategoryService _catService;

        public CategoryController(ICategoryService catService)
        {
            _catService = catService;
        }

        public async Task<IActionResult> GetAllCategories()
        {
            var cat = await _catService.GetAllCategoriesAsync();

            return View(cat);
        }

        public async Task<IActionResult> Create()
        {
            CreateCategoryDto Cat = new CreateCategoryDto();
            return View(Cat);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateCategoryDto cat)
        {
            if (ModelState.IsValid == true)
            {
                await _catService.CreateCategoriesAsync(cat);
                return RedirectToAction("GetAllCategories");

            }
            else
            {
                return View("Create", cat);
            }

        }

        public async Task<IActionResult> Edit(int id)
        {
            var editeingCat = await _catService.GetCategoryById(id);

            return View(editeingCat);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(GetAllCategoriesDto cat)
        {
            await _catService.UpdateCategoriesAsync(cat);
            return RedirectToAction("GetAllCategories");
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _catService.DeleteCategoriesAsync(id);
            return  RedirectToAction("GetAllCategories");
        }

        

    }
}

Restorant/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Restorant.DTOs.UserDtos;

namespace Restorant.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManger;

        public RoleController(RoleManager<IdentityRole> roleManger)
        {
            this.roleManger = roleManger;
        }
        public IActionResult AddRole()
        {
            return View();
        }

        [HttpPost]
        public async Task <IActionResult> AddRole(Role role)
        {
            if(ModelState.IsValid)
            {
              IdentityResult result = await roleManger.CreateAsync(new IdentityRole(role.RoleName));
                if(result.Succeeded)
                {
                    ViewBag.sucess = true;
                    return RedirectToAction("Index", "Home");
                }
                foreach(var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View("AddRole", role);
        }
        [Authorize(Roles = "Admin")]
        public IActionResult AdminAuton()
        {
            return View();
        }
    }
}

Restorant/Views/Category/Create.cshtml
@using Restorant.DTOs.CategoryDtos
@model CreateCategoryDto


<style>
    input {
        margin-top: 5px;
        margin-bottom: 15px;
        display: inline-block;
        width: 100%;
    }
</style>
<div style="width:400px">
    <form class="form" asp-action="Create" method="post">
        <h3>Add New Meal in Menu</h3>
        <br />
        <div class="form-group">
            <label asp-for="Name"></label>
            <input asp-for="Name" placeholder="Enter product name">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ImageUrl"></label>
            <input asp-for="ImageUrl" placeholder="Enter product price">
            <span asp-validation-for="ImageUrl" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description"></label>
            <br />
            <textarea asp-for="Description" type="text" placeholder="Enter product description" style="width:100%"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Add Category</button>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Restorant/Views/Category/Edit.cshtml
@using Restorant.DTOs.CategoryDtos
@model GetAllCategoriesDto

<style>
    input {
        margin-top: 5px;
        margin-bottom: 15px;
        display: inline-block;
        width: 100%;
    }
</style>
<div class="form" style="width:400px">
    <form asp-action="Edit" method="post">
        <h3>Add New Meal in Menu</h3>
        <br />
        <div class="form-group">
            <input asp-for="Id" type="hidden" />
        </div>
        <div class="form-group">
            <label asp-for="Name"></label>
            <input asp-for="Name" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ImageUrl"></label>
            <input asp-for="ImageUrl" />
            <span asp-validation-for="ImageUrl" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description" style="width:100%"></label>
            <textarea asp-for="Description" style="width:100%"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Add Category</button>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Restorant/Views/Category/GetAllCategories.cshtml
@using Restorant.DTOs.CategoryDtos
@model List<GetAllCategoriesDto>

<style>
    body {
        margin-left: 0;
        background-color: black;
    }

    h1 {
        margin-top: 100px;
        margin-bottom: 30px
    }

    td {
        white-space: nowrap
    }

    img {
        width: 60px;
        height: 60px;
    }

    p {
        margin-top: 50px;
    }

    a {
        margin: 10px;
    }
</style>

<article class="container" style="text-align:center">
    <h1 style="color:#df5f04">All Categories</h1>
    <table class="table table-bordered " style="border:2px solid #df5f04; background-color:black; color:whitesmoke">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Name
                </th>
                <th>
                    Image
                </th>

                <th>
                    Description
                </th>
                <th style="width:200px">
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in @Model)
            {
                <tr style="height:50px">
                    <td>
                        @item.Id
                    </td>
                    <td>
                        @item.Name
                    </td>
                    <td style="text-align:center">
                        <img src="~/images/@item.ImageUrl" />

                    </td>

                    <td>
                        @item.Description
                    </td>
                    <td>
                        <a asp-action=""><i class="bi bi-eye" style="color:blue"></i></a>
                        <a asp-action="Edit" asp-controller="Category" asp-route-id="@item.Id"><i class="bi bi-pencil-square" style="color:darkblue"></i></a>
                        <a asp-action="Delete" asp-controller="Category" asp-route-id="@item.Id"><i class="bi bi-trash" style="color:red"></i></a>

                    </td>
                </tr>
            }
        </tbody>
    </table>

    <p>
        <a asp-action="Create" asp-controller="Category" class="btn" style="background-color:#df5f04; margin:20px">Add Category</a>
        <a asp-action="AdminAuton" asp-controller="Role" class="btn" style="background-color:#df5f04; margin:20px">Back</a>
    </p>

</article>