Restorant/Controllers/CartController.cs
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Restorant.Application.IServices;
using Restorant.DTOs.CartDtos;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Restorant.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartService _cartSrvice;
        private readonly IMenuItemService _menuItemService;
        private readonly IOrderService _orderService;

        public CartController(ICartService cartSrvice, IMenuItemService menuItemService, IOrderService orderService)
        {
            _cartSrvice = cartSrvice;
            _menuItemService = menuItemService;
            _orderService = orderService;
        }
        [Authorize]
        public async Task<IActionResult> Cart(int id)
        {
            var meal = await _menuItemService.GetByIdAsync(id);
            var addedMeal = meal.Adapt<AddOrderItem>();
            addedMeal.MenuItemId= id;
            addedMeal.UserId =  User.FindFirstValue(ClaimTypes.NameIdentifier);
            await _cartSrvice.CreateOrderAsync(addedMeal);
           // var orders = await _cartSrvice.GetAllMenuItemsAsync();
            return RedirectToAction("MenuItems", "Meal");
        }

        public async Task<IActionResult> CartItems()
        {

             var orders = await _cartSrvice.GetAllCart();
            ViewBag.totalPrice = await _cartSrvice.TotalPrice();
            ViewBag.dicount = await _cartSrvice.Discunt();
            return View(orders);
        }

        public async Task<IActionResult> DecreaseQantity(int id)
        {
            await _cartSrvice.DecreasQantity(id);

            return RedirectToAction("CartItems"); 
        }
        public async Task<IActionResult> IcreaseQantity(int id)
        {
            await _cartSrvice.IncreasQantity(id);

            return RedirectToAction("CartItems");
        }

        [Authorize]
        public async Task<IActionResult>CreateOrder()
        {
           var userId =  User.FindFirstValue(ClaimTypes.NameIdentifier);
           var cart =  await _orderService.CreateAsync(userId);
            var order = await _orderService.GetOrderByUserId(userId);
            await  _cartSrvice.DeleteAsync(cart, order);
            return RedirectToAction("CartItems");
        }


    }
}

Restorant/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Restorant.Application.IServices;
using System.Security.Claims;

namespace Restorant.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;

        public OrderController(IOrderService orderService)
        {
            _orderService = orderService;
        }

        [Authorize]
        public async Task<IActionResult> GetUserOrders()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var allOrders =await _orderService.GetOrdersByUserId(userId);
            return View(allOrders);
        }
    }
}

Restorant/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Restorant</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Restorant.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css"/>
</head>
<body >
    <header >
        <nav class="navbar bg-body-tertiary fixed-top" style="background-color:black;border-bottom:1px solid #df5f04 ">
            <div class="container-fluid head_cont">
                <h4><a class="navbar-brand" href="#" style="color:#df5f04">My Restuarant</a></h4>
                <div id="header">
                    <ul class="header_ul">
                        <li class="li_marg"><h5><a asp-action="Index" asp-controller="Home" class="link navbar-brand" style="color:#df5f04">Home</a></h5> </li>
                        <li class="li_marg"><h5><a asp-action="MenuItems" asp-controller="Meal" class="link navbar-brand" style="color:#df5f04">Menu</a></h5> </li>
                        <li class="li_marg"><h5> <a asp-action="Index" asp-controller="Home" class="navbar-brand" style="color:#df5f04">Category</a></h5> </li>
                        <li class="li_marg"> <h5><a class="navbar-brand" style="color:#df5f04">About Us</a></h5> </li>
                        <li class="li_marg"> <h5><a asp-action="GetUserOrders" asp-controller="Order" class="navbar-brand" style="color:#df5f04">Your Orders</a></h5> </li>
                       
                        
                    </ul>
                </div>

                @* <div>
                    <span class="navbar-toggler-icon" style="height:"><a asp-action="Register" asp-controller="Account" class="" style="color:#e9ded8;">SignIn</a></span>

                </div> *@
                <div>
                    <span class="navbar-toggler-icon" style="height:50px"><a asp-action="CartItems" asp-controller="Cart"><i class="bi bi-cart2" style="font-size:30px; color:#df5f04"></i></a></span>

                </div>
                <button style="background-color:#df5f04 ;border-color:#e9ded8" id="toggler" class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                    <span  class="navbar-toggler-icon"><i class="bi bi-list" style="color:black"></i></span>
                </button>
               
                <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel" style="background-color:#df5f04">
                    <div class="offcanvas-header">
                        <h4 class="offcanvas-title" id="offcanvasNavbarLabel" style="color:#e9ded8">My Restuarant</h4>
                        <button type="button" class="btn-close" id="close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                            <li class="nav-item">
                                <h5 class="cont-icon" style="display:flex">
                                    <span class="icon" style=""><i class="bi bi-house-heart-fill"></i></span>
                                    <span style="height:50px"><a class="nav-link active" asp-action="Index" asp-controller="Home" aria-current="page" style="color:#e9ded8">Home</a></span>
                                </h5>
                            </li>
                            <li class="nav-item">
                                <h5 class="cont-icon">
                                    <span class="icon" style=""><i class="bi bi-fork-knife icon"></i></span>

                                    <span style="height:50px"> <a class="nav-link col" asp-action="MenuItems" asp-controller="Meal" style="color:#e9ded8">Menu Items</a></span>
                                </h5>
                            </li>
                            <li class="nav-item">
                                <h5 class="cont-icon">
                                    <span class="icon">
                                        <i class="bi bi-grid-fill icon"></i></span>
                                    <span style="height:50px"><a class="nav-link col " href="#" style="color:#e9ded8">Categories</a></span>
                                </h5>
                            </li>
                            <li class="nav-item">
                                <h5 class="cont-icon">
                                    <span class="icon">
                                        <i class="bi bi-people-fill "></i></span>
                                    <span style="height:50px"><a class="nav-link " href="#" style="color:#e9ded8">About Us</a></span>
                                </h5>
                            </li>
                            <li class="nav-item">
                                <h5 class="cont-icon">
                                    <span class="icon">
                                        <i class="bi bi-telephone-plus-fill "></i></span>
                                    <span style="height:50px"> <a class="nav-link " href="#" style="color:#e9ded8">Conect Us</a></span>
                                
                                </h5>
                            </li>
                            <li class="nav-item">
                                <h5 class="cont-icon">
                                    <a asp-action="RoleLogin" asp-controller="Account" class="btn btn-close-white">Admin</a>

                                </h5>
                                <h5 class="cont-icon">
                                    <a asp-action="SignOut" asp-controller="Account" class="btn btn-close-white">SignOut</a>

                                </h5>
                            </li>

                            <li class="nav-item dropdown">
                                @* <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Dropdown
                                </a> *@
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="#">Action</a></li>
                                    <li><a class="dropdown-item" href="#">Another action</a></li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                                </ul>
                            </li>

                        </ul>
                        @* <form class="d-flex mt-3" role="search">
                            <div class="input-group flex-nowrap">
                                <span class="input-group-text" id="addon-wrapping "><i class=" fa-solid fa-magnifying-glass"></i></span>
                                <input type="search" class=" search form-control" placeholder="Search" aria-label="Username" aria-describedby="addon-wrapping">
                            </div>
                            <button class="btn btn-outline-success" type="submit">Search</button>
                        </form> *@
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div style="">
        <main >
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color:black; position:relative">
        <article class="container" style=""; font-size:20px;padding-top:20px">
            <h3>Contact Us</h3>
            <div><i class="bi bi-facebook" style="color:darkblue;margin-right:10px; font-size:25px"></i>Facebooc</div>
            <div><i class="bi bi-whatsapp" style="color:forestgreen;margin-right:10px; font-size:25px"></i>010234658</div>
            <div><i class="bi bi-telephone-fill" style="color:forestgreen;margin-right:10px; font-size:25px"></i>011235496</div>
            <div><i class="bi bi-geo-alt-fill" style="color:darkblue;margin-right:10px; font-size:25px"></i>Location</div>

        </article>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>